### ISSUE TITLE
Session resume appears to be broken for me

### ISSUE THREAD

**Issue by latentflip** [github/session-resume#6]
session-resume on an issue comment for example doesn't seem to be working for me properly in chrome and I just lost a bunch of text from accidentally closing a tab :(

**These things work**
1. Type in an issue comment, refresh the tab, text is still there
2. Type in an issue comment, close the tab, reopen with `cmd-shift-t`, text is still there

I suspect the browser is doing this though, rather than session-resume.

**This does not work**
1. Type in an issue comment, close the tab, open a new tab, navigate to issue url - issue comment box is empty.
2. Have two tabs to `github.com`, in one type in an issue comment box, close the tab. In the other `sessionStorage` is still empty.

**Comment by dgreif** [comment]
I believe these issues stem from the fact that `session-resume` uses `sessionStorage` instead of `localStorage` on github.com. `sessionStorage` behaves exactly as you described, retaining stored values within a given tab only (even if it's closed and reopened), but not sharing them with other/new tabs. We could consider using `localStorage` instead, but I _think_ `sessionStorage` was chosen specifically because we didn't want draft inputs to leak if you closed a tab on a shared computer.
